
server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KG?serverTimezone=GMT%2b8
    username: root
    password: Xzy030317
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mabatis的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path:  /Users/autt/Desktop/uploadfiles/